Lock oj gem to version < 3
Versions >= 3 require Ruby 1.9:

```
custom.c:373:15: error: use of undeclared identifier 'rb_eEncodingError'
custom.c:860:29: error: use of undeclared identifier 'RUBY_T_FIXNUM'
```

Versions >= 3.3.5 require Ruby 2.2:
https://github.com/ohler55/oj/commit/de0dd2bfb09d7eb5300fe9e7d7236e94ae474cd1